### ISSUE TITLE
processes > 1 not working

### ISSUE THREAD

**Issue by Sozialarchiv** [CLARIAH/COW#92] opened 2020-08-28 10:05 UTC
## Environement:

Windows 10
Python 3.8
Cow 2020 and 0.65

## How to reproduce:

```
from cow_csvw.csvw_tool import COW
import os

cwd = os.path.dirname(os.path.realpath(__file__))
csvPath = os.path.join(cwd, "data", "test.csv")

COW(mode='convert', files=[csvPath], delimiter=',', processes=4, output_format="turtle" )
```

If processes is set to 1 everything is working.

## Error

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by melvinroest** [comment] 2020-10-12 09:22
@Sozialarchiv: could you try it again with the new version of CoW?

`pip3 install cow-csvw # Python 3 only`

**Comment by melvinroest** [comment] 2020-11-06 09:05
I can't reproduce this on Ubuntu 20.04 with CoW 0.66.2 
What I did in the `python3` shell is this:

```
# Go to the directory of your CSV file
from cow_csvw.csvw_tool import COW
COW(mode='convert', files=["some_data_50000_lines.csv"], delimiter=',', processes=9, output_format="nquads" )
```

This reads 45K lines in one go and picks up the final 5K later.

**Comment by melvinroest** [comment] 2020-11-06 09:30
@Sozialarchiv: I also tested on Windows 10 with Python 3.7.9 with the development version of CoW (as my Windows VM does not have `cow_tool` installed) and couldn't find any issues there. 

I'd suggest to build the `2020` version. If the issue persists feel free to contact me and we'll take a look at it together (I suggest via video chat). If a bug is found, then I suggest to reopen the issue.

I'm closing it for now.

**Closed by melvinroest** 2020-11-06 09:30 UTC
Labels: bug
