### ISSUE TITLE
illegal filenames on Windows doing pip install

### ISSUE THREAD

**Issue by albertmeronyo** [CLARIAH/COW#61] opened 2018-09-25 07:16 UTC
The character ':' is forbidden in Windows filenames and hence pip fails to upgrade cow_csvw when doing $ pip install cow_csvw --upgrade on Windows (should also fail to fresh install):

`Could not install packages due to an EnvironmentError: [Errno 22] invalid mode ('wb') or filename: 'c:\\users\\ruben\\appdata\\local\\temp\\pip-install-1vez4s\\cow-csvw\\src/tests/occupation_link_test.csv-metadata.json_2017-11-04T09:27:45.920447'`

This seems to demand to change these filenames, as well as the code that generates them.

**Comment by RubenSchalk** [comment] 2018-09-26 07:06
When deleting COW and reinstalling via pip I still get this error, perhaps because these files still are somewhere on my drive. Any solutions? Would be good if I can update COW through pip update in the future.

**Comment by melvinroest** [comment] 2020-10-14 13:13
I installed cow with `pip3 install cow-csvw` but I couldn't reproduce this.

Is this still an issue?

**Comment by melvinroest** [comment] 2020-10-27 10:49
@RubenSchalk let me know if this is still an issue. I'm closing it for now.

**Closed by melvinroest** 2020-10-27 10:49 UTC
Labels: deployment
