### ISSUE TITLE
missing slash in provenance URI

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#57] opened 2018-04-30 18:22 UTC
Hi, I think this is a 'known bug', but not yet reported:

In the subject position of the provenance, nanopublication and asseration graph (meta), there is a slash missing between the base URI and file name: 
`<https://iisg.amsterdamimf_gdppc/provenance/`

E.g. the example file produces these faulty triples:
```
<https://iisg.amsterdamimf_gdppc/assertion/0f8040d8/2018-04-30T18:17> <http://www.w3.org/ns/prov#wasDerivedFrom> <https://iisg.amsterdam0f8040d82d7115e927c4ae5a417e7bfc83aa60bd> <https://iisg.amsterdamimf_gdppc/provenance/0f8040d8/2018-04-30T18:17> .
<https://iisg.amsterdamimf_gdppc/nanopublication/0f8040d8/2018-04-30T18:17> <http://www.w3.org/ns/prov#generatedAtTime> "2018-04-30T18:17:00"^^<http://www.w3.org/2001/XMLSchema#dateTime> <https://iisg.amsterdamimf_gdppc/pubinfo/0f8040d8/2018-04-30T18:17> .
<https://iisg.amsterdamimf_gdppc/nanopublication/0f8040d8/2018-04-30T18:17> <http://www.w3.org/ns/prov#wasGeneratedBy> <https://github.com/CLARIAH/wp4-converters> <https://iisg.amsterdamimf_gdppc/pubinfo/0f8040d8/2018-04-30T18:17> .
<https://iisg.amsterdamimf_gdppc/provenance/0f8040d8/2018-04-30T18:17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.nanopub.org/nschema#Provenance> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdamimf_gdppc/assertion/0f8040d8/2018-04-30T18:17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.nanopub.org/nschema#Assertion> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdamimf_gdppc/nanopublication/0f8040d8/2018-04-30T18:17> <http://www.nanopub.org/nschema#hasProvenance> <https://iisg.amsterdamimf_gdppc/provenance/0f8040d8/2018-04-30T18:17> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdam0f8040d82d7115e927c4ae5a417e7bfc83aa60bd> <https://iisg.amsterdam/vocab/sha1_hash> "0f8040d82d7115e927c4ae5a417e7bfc83aa60bd"^^<http://www.w3.org/2001/XMLSchema#string> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdamimf_gdppc/nanopublication/0f8040d8/2018-04-30T18:17> <http://www.nanopub.org/nschema#hasAssertion> <https://iisg.amsterdamimf_gdppc/assertion/0f8040d8/2018-04-30T18:17> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdamimf_gdppc/pubinfo/0f8040d8/2018-04-30T18:17> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.nanopub.org/nschema#PublicationInfo> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdam0f8040d82d7115e927c4ae5a417e7bfc83aa60bd> <https://iisg.amsterdam/vocab/path> "/tmp/imf_gdppc.csv"^^<http://www.w3.org/2001/XMLSchema#string> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .
<https://iisg.amsterdamimf_gdppc/nanopublication/0f8040d8/2018-04-30T18:17> <http://www.nanopub.org/nschema#hasPublicationInfo> <https://iisg.amsterdamimf_gdppc/pubinfo/0f8040d8/2018-04-30T18:17> <urn:uuid:74a50cdf-d0f1-47bd-ba6d-f2497df2be83> .

```

**Comment by RoderickvanderWeerdt** [comment] 2018-08-31 12:35
This seems to be caused by the sdr namespace in the "namespaces.yaml" file, here it misses the trailing slash. 

The slash is only missing in the implementation in the src folder, it seems to be already fixed in the cow folder version. 
The resulting combination from #60 should also fix this issue.

**Closed** 2018-09-24 12:15 UTC
Labels: bug
